version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  mongoexpress:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  app:
    image: issue-tracker-app:latest
    container_name: issue-tracker-app
    ports:
      - "8083:8083"
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local